version: '3.8'

services:
  web:
    build: .
    expose:
      - "80"
    labels:
      coolify.proxy: "true"
      coolify.port: "80"
      coolify.type: "docker"           # <-- Forces Coolify to treat as full image
      coolify.domain: "old.dreamstorchlight.org"